{% set name = "mpl_qt_viz" %}
{% set version = "1.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpl_qt_viz-{{ version }}.tar.gz
  sha256: 07f464939b8ac0b74a319908c52b3be69cf01b5abb4c524845a8e26ef55bd803

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - matplotlib-base
    - numpy
    - opencv
    - pyqt
    - python >=3.7
    - scikit-image
    - scipy
    - shapely
    - cycler

test:
  imports:
    - mpl_qt_viz

about:
  home: https://github.com/nanthony21/mpl_qt_viz
  summary: A Python package providing enhanced data visualization and ROI selection built on top of Matplotlib and PyQt5.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - nanthony21
